### PR TITLE
Out of sample predict

### PR DESCRIPTION
**Pull request by timvink**
Hi kaushikrch,

My colleagea Gilles Verbockhaven and I made an edit to RUCM to be able to predict out of sample. This would close issues #2 and #8 . 

Could you have a look and merge if you like it? 

Kind regards,

Tim

### CODE REVIEW

**Comment by timvink** [comment]
Hi kaushikrch,

Have you had a chance to look at this yet? Looking forward :)

Tim

**Comment by kaushikrch** [comment]
Apologies, had been caught up with work. Will take a look over the weekend.

**Review by kaushikrch — APPROVED** [review]

**Comment by kaushikrch** [comment]
Thanks Tim and Gilles.

**Comment by timvink** [comment]
Thanks. FYI, looks like the update to the README wasn't merged though.

**Comment by timvink** [comment]
Update: the actual update to `predict.ucm()` is also not updated yet. Perhaps something went wrong with the merge.. shall I open another pull request?

**Comment by kaushikrch** [comment]
Probably that would be helpful. I think something went wrong while merging.

**Pull request closed without merging**
